### ISSUE TITLE
Configuration questions

### ISSUE THREAD

**Issue by averlon** [YolfTypo3/SavCharts#4]
Hi Laurent,
[av_chart2.txt](https://github.com/YolfTypo3/SavCharts/files/7147850/av_chart2.txt)
[av_chart3.txt](https://github.com/YolfTypo3/SavCharts/files/7147851/av_chart3.txt)

I wonder if you could help me with some configuration issues on Typo3 SAVCHARTS.

1)	Please have a look at the chart2.xml I have attached. Although min and max are set, the scaling of the y-axes is shown on the website different (see on www.averlon.de, 2nd graph).
I am sure, this has to do with some scaling. Anyhow, it is not a big deal, but I would like to have the y-Axes as defined in min and max.
2)	Please have a look at the chart3.xml I also attached.
In this, I wanted to add some setting on “borderDash” for one of the lines like “ - - - - - - - - -“ – but failed so far. Probably you could help me with the correct format of the setting.

Thanks in advance!

Karl-Heinz

**Comment by YolfTypo3** [comment]
1. The FAQ section of the documentation provides an example for the configuration of the y-axis https://docs.typo3.org/p/yolftypo3/sav-charts/master/en-us/FAQ/Index.html. **Be sure to select your SAV Charts version** since the latest version uses Charts.js 3. The configuration for the axis changed in this new version.

Depending on your version  your configuration should be either `<item key="yAxis"><item key="0"><item key="ticks">.....</item></item></item>` or `<item key="y">.... </item>`.

2.  In your dataset your have to add the borderDash configuration which is an array with two values. So you need to write

```
          <item key="borderDash">
                  <item key="0" value="5" />
                  <item key="1" value="15" />    
            </item>
```
